-- ============================================================
-- MAGNUM — Migración: tabla de marcas
-- Ejecutar una sola vez en: Supabase → SQL Editor → Run
-- (No borra datos existentes)
-- ============================================================

create table if not exists brands (
  id int generated by default as identity primary key,
  name text not null unique,
  sort_order int default 0
);

alter table brands enable row level security;

drop policy if exists "public read brands" on brands;
create policy "public read brands" on brands for select using (true);

drop policy if exists "admin write brands" on brands;
create policy "admin write brands" on brands for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into brands (name, sort_order) values
  ('Benelli', 1), ('CZ', 2), ('Canik', 3), ('Franchi', 4),
  ('Glock', 5), ('Mossberg', 6), ('Smith & Wesson', 7),
  ('Spec Ops', 8), ('Volunteer', 9)
on conflict (name) do nothing;
