-- ============================================================
-- MAGNUM GUNS & AMMO SHOP — Esquema Supabase
-- Pegar este archivo completo en: Supabase → SQL Editor → Run
-- ============================================================

-- ----- Tablas -----
create table if not exists products (
  id int generated by default as identity primary key,
  name text not null,
  slug text,
  brand text,
  category text,
  caliber text,
  image text,
  gallery text[] default '{}',
  short_desc text,
  full_desc text
);

create table if not exists paquetes (
  id int generated by default as identity primary key,
  title text not null,
  price text,
  items text[] default '{}',
  featured boolean default false,
  sort_order int default 0
);

create table if not exists slides (
  id int generated by default as identity primary key,
  kicker text,
  title text,
  accent text,
  body text,
  image text,
  btn1_text text,
  btn1_url text,
  btn2_text text,
  btn2_url text,
  sort_order int default 0,
  active boolean default true
);

-- ----- Row Level Security -----
alter table products enable row level security;
alter table paquetes enable row level security;
alter table slides enable row level security;

-- Lectura pública
drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (true);
drop policy if exists "public read paquetes" on paquetes;
create policy "public read paquetes" on paquetes for select using (true);
drop policy if exists "public read slides" on slides;
create policy "public read slides" on slides for select using (true);

-- Escritura solo para usuarios autenticados (el admin)
drop policy if exists "admin write products" on products;
create policy "admin write products" on products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "admin write paquetes" on paquetes;
create policy "admin write paquetes" on paquetes for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "admin write slides" on slides;
create policy "admin write slides" on slides for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- ----- Datos semilla: productos -----
delete from products;
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (1, $$M&P 22 Compact$$, $$m-p-22-compact$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 22LR$$, $$productos/m-p-22-compact.jpg$$, '{}'::text[], $$Modelo: M&amp;P®22 COMPACT
SKU: 10199
Tamaño del marco: Compacto
Calibre: .22 LR
Acción: Acción simple (Martillo interno)
Capacidad: 10+1 rondas$$, $$Modelo: M&amp;P®22 COMPACT
SKU: 10199
Tamaño del marco: Compacto
Calibre: .22 LR
Acción: Acción simple (Martillo interno)
Capacidad: 10+1 rondas
Longitud del cañón: 3.56" (9.04 cm)
Mira delantera: Punto blanco
Mira trasera: 2 puntos blancos -
Ajustable con
ornillo para viento y elevación
Overall Length: 7.25" (18.4 cm)
Overall Height: 5.03" (12.8 cm)
Overall Width: 1.48" (3.8 cm)
Grip: Polymer
Weight: 15.3 oz. (433.8 g)
Empty Mag Weight: 1.7 oz (48.2 g)
Barrel Material: Carbon Steel
Slide Material: Aluminum Alloy
Frame Material: Polymer
Finish: Black, Hard Coat Anodize
UPC Code: 022188866506$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (2, $$M&P 22 COMPACT SERIES$$, $$m-p-22-compact-series$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 22LR$$, $$productos/m-p-22-compact-series.jpg$$, '{}'::text[], $$SKU: 10242
Model: M&amp;P®22 COMPACT CERAKOTE® FLAT DARK EARTH THREADED BARREL
Caliber: 22 LR
Capacity: 10+1$$, $$SKU: 10242
Model: M&amp;P®22 COMPACT CERAKOTE® FLAT DARK EARTH THREADED BARREL
Caliber: 22 LR
Capacity: 10+1
Safety: Thumb Safety
Barrel Length: 3.3"
Overall Length: 5.03"
Front Sight: White Dot

Rear Sight: White Two Dot
Action: Internal Hammer Fire
Grip: Polymer
Weight: 32 oz
Barrel Material: Stainless Steel
Frame Material: Polymer
Slide Finish: Matte Bl
FRAME FINISH: FDE$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (3, $$M&P 22 CAMPACT SERIES$$, $$m-p-22-campact-series$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 380$$, $$productos/m-p-22-campact-series.jpg$$, '{}'::text[], $$Model: BG380
SKU: 109381
Frame Size: Sub Compact
Caliber: .380 Auto
Action: Double Action Only (Hammer Fired)
Capacity: 6+1 Rounds$$, $$Model: BG380
SKU: 109381
Frame Size: Sub Compact
Caliber: .380 Auto
Action: Double Action Only (Hammer Fired)
Capacity: 6+1 Rounds
Overall Length: 5.25" (13.3 cm)
Weight: 12.0 oz. (340.2 g)
Barrel Length: 2.75" (7.0 cm)
Barrel Material: Stainless Steel
Slide Material: Stainless Steel
Frame Material: Polymer
Finish: Matte Black
Front Sight: Stainless Steel Drift Adjustable
Rear Sight: Stainless Steel Drift Adjustable
UPC Code: 022188093810$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (4, $$M&P® BODYGUARD® 380 INTEGRATED CRIMSON TRACE® LASE$$, $$m-p-bodyguard-380-integrated-crimson-trace-lase$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 380$$, $$productos/m-p-bodyguard-380-integrated-crimson-trace-lase.jpg$$, '{}'::text[], $$Model: BG380 – Crimson Trace®
SKU: 10048
Frame Size: Sub Compact
Caliber: .380 Auto
Action: Double Action Only (Hammer Fired)
Capacity: 6+1 Rounds$$, $$Model: BG380 – Crimson Trace®
SKU: 10048
Frame Size: Sub Compact
Caliber: .380 Auto
Action: Double Action Only (Hammer Fired)
Capacity: 6+1 Rounds
Barrel Length: 2.75” (7.0 cm)
Front Sight: Stainless Steel Drift Adjustable
Rear Sight: Stainless Steel Drift Adjustable
Overall Length: 5.25” (13.3 cm)
Grip: Polymer
Weight: 12.3 oz. (348.7 g)
Barrel Material: Stainless Steel
Slide Material: Stainless Steel
Frame Material: Polymer
Finish: Matte Black
UPC Code: 022188864823
OTHER FEATURES
• Crimson Trace® Integrated Laser
• Stainless Steel Drift Adjustable Sights
• Two MagazinesIncluded (Finger Groove and Flat
Butt Plate)
• Ergonomic Grip
• High-Strength Polymer Frame
• External Takedown Lever &amp; Slide Stop
• Manual Thumb Safety
• Double Action Fire Control (2nd Strike Capability)
• Stainless Steel Barrel &amp; Slide
• Adjust Laser Without Any Disassembly of Firearm$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (5, $$M&P®5.7 TWO-TONE INTEGRATED CRIMSON TRACE® LASE$$, $$m-p-5-7-two-tone-integrated-crimson-trace-lase$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 5.7$$, $$productos/m-p-5-7-two-tone-integrated-crimson-trace-lase.jpg$$, '{}'::text[], $$Modelo: M&amp;P®5.7 Two-tone w/No Manual Thumb Safety
UPC Code: 022188895988
Frame Size : Full-Size
Action: Internal Hammer-Fired,
Gas-Operated$$, $$Modelo: M&amp;P®5.7 Two-tone w/No Manual Thumb Safety
UPC Code: 022188895988
Frame Size : Full-Size
Action: Internal Hammer-Fired,
Gas-Operated
Rifling: 1:9˝ Twist Rate
Front Sight: Steel, White Dot
Rear Sight: Steel, White 2-Dot
Overall Width: 1.1˝ (2.79 cm)
Overall Height: 5.25˝ (13.3 cm)
Overall Length: 8.5˝ (21.6 cm)
Sight Radius: 7.125˝ (18.1 cm)
Grip: Slim, textured
Pistol Weight: 26.7 oz. (756.9 g)
Mag. Weight:3.2 oz. (90.7 g)
Barrel: 5.0˝ (12.7 cm) Stainless Steel Armornite® Finish
Slide: Stainless Steel w/Armornite® Finish
Frame: Flat Dark Earth Polymer$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (6, $$M&P®5.7 FLAT DARK EARTH (FDE)$$, $$m-p-5-7-flat-dark-earth-fde$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 5.7$$, $$productos/m-p-5-7-flat-dark-earth-fde.jpg$$, '{}'::text[], $$Modelo: M&amp;P®5.7 Flat Dark Earth (FDE)
UPC Code: 022188895490
Frame Size : Full-Size
Action: Internal Hammer-Fired, Gas-operated semi-auto$$, $$Modelo: M&amp;P®5.7 Flat Dark Earth (FDE)
UPC Code: 022188895490
Frame Size : Full-Size
Action: Internal Hammer-Fired, Gas-operated semi-auto
Rifling: 1:9˝ Twist Rate
Front Sight: Steel, White Dot
Rear Sight: Steel, White 2-Dot
Overall Width: 1..1˝ (2.79 cm)
Overall Height: 5.25˝ (13.3 cm)
Overall Length: 8.5˝ (21.6 cm)
Sight Radius: 7.125˝ (18.1 cm)
Grip: Slim, textured
Pistol Weight: 26.7 oz. (756.9 g)
Mag. Weight:3.2 oz. (90.7 g)
Barrel: 5.0˝ (12.7 cm) Stainless Steel Armornite® Finish
Slide: Stainless Steel with Cerakote® FDE Finish
Frame: Polymer Flat Dark Earth$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (7, $$SMITH & WESSON SD9 2.0$$, $$smith-wesson-sd9-2-0$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/smith-wesson-sd9-2-0.jpg$$, '{}'::text[], $$Model: Smith &amp; Wesson SD9 2.0
Front Sight: White Dot
UPC Code: 022188896800
Frame Size: Compact
Action: Striker-Fired$$, $$Model: Smith &amp; Wesson SD9 2.0
Front Sight: White Dot
UPC Code: 022188896800
Frame Size: Compact
Action: Striker-Fired
Rifling: 1:18.75 twist
Rear Sight: 2 White Dots, drift adjustable
Overall Width: 1.29" (3.3 cm)
Overall Height: 5.5" (12.7 cm)
Overall Length: 7.2" (18.3 cm)
Sight Radius: 6.19" (15.7 cm)
Grip: Textured sides and front and back
Pistol Weight: 22.7 oz. (643 g)
Comes with: (1) 16-round magazine
Magazine: 16-round
Barrel: 4" (10.2 cm) Stainless Steel
Slide: Stainless Steel w/Satin Finish
Frame: Black Polymer$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (8, $$MOSSBERG MC2C OPTIC READY$$, $$mossberg-mc2c-optic-ready$$, $$Mossberg$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/mossberg-mc2c-optic-ready.jpg$$, '{}'::text[], $$sku 89031
Caliber 9MM
Action Type Semi-Auto
Usage Security
Barrel Length 3.9"
Barrel Finish 416 Stainless Steel | DLC
Capacity 14+1; 16+1$$, $$sku 89031
Caliber 9MM
Action Type Semi-Auto
Usage Security
Barrel Length 3.9"
Barrel Finish 416 Stainless Steel | DLC
Capacity 14+1; 16+1
Frame Finish Matte Black
Frame Type Compact
Height 4.90"
Length 7.10"
Sights White 3-Dot / Optic-Ready
Front Sight White Dot, Drift Adj. Dovetail Sight
Rear Sight Dual White Dot, Drift Adj. Dovetail Sight
Sight Radius 6.40"
Slide Finish DLC - Black
Trigger Flat Profile
Trigger Pull Approx. 5.5 lbs
Trigger Travel 0.5"
Safety Integrated Trigger Blade
Twist 1:16 RH
Width 1.10"
Weight 21 oz (Unloaded), 29 oz (Loaded)$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (9, $$M&P 9 SHIELD PLUS$$, $$m-p-9-shield-plus$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/m-p-9-shield-plus.jpg$$, '{}'::text[], $$Model: M&amp;P®9 SHIELD™ PLUS
SKU: 13246
Frame Size: Micro-Compact
Caliber: 9mm
Action: Striker-Fired
Capacity: 13+1 and 10+1 Rounds$$, $$Model: M&amp;P®9 SHIELD™ PLUS
SKU: 13246
Frame Size: Micro-Compact
Caliber: 9mm
Action: Striker-Fired
Capacity: 13+1 and 10+1 Rounds
Barrel Length: 3.1˝ (7.9 cm)
Rifling: 1:10˝ - 5 RH
Front Sight: White Dot
Rear Sight: White 2-Dot
Frame Width (Less Controls): 1.1˝ (2.8 cm)
Overall Height: .94˝ (2.4 cm)
Overall Length: 4.6˝ (11.7 cm)
Sight Radius: 6.1˝ (15.5 cm)
Grip: Polymer
Weight: 20.2 oz. (572.7 g)
Magazine Weight:
13 Round: 2.6 oz. (6.6 g)
10 Round: 2.2 oz. (6.6 g)
Barrel Material: Stainless Steel with Armornite® Finish
Slide Material: Stainless Steel with Armornite® Finish
Slide Finish: Matte Black
Frame Material: Polymer
Frame Finish: Matte Black
UPC Code: 02218888492$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (10, $$M&P 9 SHIELD PLUS OR$$, $$m-p-9-shield-plus-or$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/m-p-9-shield-plus-or.jpg$$, '{}'::text[], $$Modelo: M&amp;P®9 SHIELD™ PLUS
SKU: 13536
Tamaño del armazón: Micro-Compact
Calibre: 9mm
Acción: Striker-Fired
Capacidad del cargador: 13+1 y 10+1 rondas$$, $$Modelo: M&amp;P®9 SHIELD™ PLUS
SKU: 13536
Tamaño del armazón: Micro-Compact
Calibre: 9mm
Acción: Striker-Fired
Capacidad del cargador: 13+1 y 10+1 rondas
Longitud del cañón: 3.1˝ (7.9 cm)
Estrías del cañón: 1:10˝ - 5 RH
Mira delantera: Orange Ring Tritium Night Sight
Mira trasera: Black Tritium Night Sight
Ancho del armazón (sin controles): 1.1˝ (2.8 cm)
Altura total: .94˝ (2.4 cm)
Longitud total: 6.1˝ (15.5 cm)
Radio de la mira: 5.3˝ (13.5 cm)
Empuñadura: Polymer
Peso total: 19.9 oz. (564.2 g)
Peso del cargador:
Cargador de 13 rondas: 2.6 oz. (6.6 g)
Cargador de 10 rondas: 2.2 oz. (6.6 g)
Material del cañón: Acero inoxidable con acabado Armornite®
Material del corredera: Acero inoxidable con acabado Armornite®
Acabado de la corredera: Negro mate
Material del armazón: Polymer
Acabado del armazón: Negro mate
Código UPC: 022188888669$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (11, $$CSX ® ™$$, $$csx$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/csx.jpg$$, '{}'::text[], $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 28"
Sight/Base: Dual Bead$$, $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 28"
Sight/Base: Dual Bead
Choke: Modified Tube
LOP Type: Fixed
LOP: 14.5"
Barrel Finish: Blued
Stock Finish: Synthetic (Black)
Weight: 19.5 oz. (552.8 g) with 12 Round Mag
Magazine Weight: 2.4 oz. (68.0 g) - 12 Round Mag
Barrel Material: Stainless Steel with Armornite® Finish
Slide Material: Stainless Steel with Armornite® Finish
Slide Finish: Matte Black
Frame Material: Aluminum Alloy
Frame Finish: Matte Black
UPC Code: 022188885200$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (12, $$SPEC OPS 2023 BULL SHARK GREY$$, $$spec-ops-2023-bull-shark-grey$$, $$Spec Ops$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/spec-ops-2023-bull-shark-grey.jpg$$, '{}'::text[], $$3 PROVEEDORES
CALIBRE: 9MM
CAÑON ROSCADO$$, $$3 PROVEEDORES
CALIBRE: 9MM
CAÑON ROSCADO$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (13, $$M&P 9 M2.0 COMPACT$$, $$m-p-9-m2-0-compact$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/m-p-9-m2-0-compact.jpg$$, '{}'::text[], $$Modelo: M&amp;P®9 M2.0™ Compact
SKU: 13570
Tamaño del Marco: Compacto
Calibre: 9mm
Acción: Striker-Fired
Capacidad: 15+1 rondas$$, $$Modelo: M&amp;P®9 M2.0™ Compact
SKU: 13570
Tamaño del Marco: Compacto
Calibre: 9mm
Acción: Striker-Fired
Capacidad: 15+1 rondas
Longitud del Cañón: 3.6˝ (9.1 cm)
Ánima del Cañón: 1:10” RH, 5 Estrías
Mira Frontal: Punto Blanco - Alto
Mira Trasera: 2 Puntos Blancos - Altos
Ancho del Marco (Menos Controles): 1.16˝ (2.9 cm)
Altura Total: 5.0˝ (12.7 cm)
Longitud Total: 6.8˝ (17.3 cm)
Radio de la Mira: 5.9˝ (16.3 cm)
Agarre: Polímero
Peso: 25.9 oz. (734.3 g)
Material del Cañón: Acero Inoxidable con Acabado Armornite®
Material del Slide: Acero Inoxidable con Acabado Armornite®
Acabado del Slide: Negro Mate
Material del Marco: Polímero
Acabado del Marco: Negro Mate
Código UPC: 022188889543$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (14, $$COMPETITOR M2.0-OR EDICION CAÑON DE 5” COLOR NEGRO$$, $$competitor-m2-0-or-edicion-canon-de-5-color-negro$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/competitor-m2-0-or-edicion-canon-de-5-color-negro.webp$$, '{}'::text[], $$SKU: 13199
Frame Size: Full-size
Caliber: 9mm Luger
Action: Striker-Fired
Capacity: 17+1 Roun$$, $$SKU: 13199
Frame Size: Full-size
Caliber: 9mm Luger
Action: Striker-Fired
Capacity: 17+1 Rounds
Barrel Length: 5.0˝ (12.7 cm)
Rifling: 1:10˝
Front Sight: Green Fiber Optic
Rear Sight: Serrated, Blacked-out
Frame Width: 1.3˝ (3.3 cm)
Overall Height: 5.5˝ (14 cm)
Overall Length: 8.25˝ (21 cm)
Sight Radius: 7.25˝ (18.4 cm)
Grip: Interchangeable Backstrap Inserts (4)
Weight: 29.3 oz. (830.7 g)
Magazine Weight: 3.1 oz. (87.9 g)
Barrel Material: Stainless Steel with Armornite® Finish
Slide Material: Stainless Steel
Slide Finish: Tungsten Gray Cerakote®
Frame Material: 7075-T6 Aluminum
Frame Finish: Tungsten Gray Cerakote®
UPC Code: 022188884777$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (15, $$SUBCOMPACT 3.4" OPTIC READY$$, $$subcompact-3-4-optic-ready$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/subcompact-3-4-optic-ready.jpg$$, '{}'::text[], $$(2) PROVEDORES"
RONDAS 10+1
RONDAS 13+1
9MM
SIN SEGURO$$, $$(2) PROVEDORES"
RONDAS 10+1
RONDAS 13+1
9MM
SIN SEGURO$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (16, $$MC-2 COMPACT 3.9 COLOR BITONO CON SEGURO. INCLUYE 4 MAGS$$, $$mc-2-compact-3-9-color-bitono-con-seguro-incluye-4-mags$$, $$Mossberg$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/mc-2-compact-3-9-color-bitono-con-seguro-incluye-4-mags.jpg$$, '{}'::text[], $$(4) PROVEDORES
2 RONDAS 10+1
2 RONDAS 13+1
9MM
CON SEGURO$$, $$(4) PROVEDORES
2 RONDAS 10+1
2 RONDAS 13+1
9MM
CON SEGURO$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (17, $$500 ATI TACTICAL$$, $$500-ati-tactical$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/500-ati-tactical.jpg$$, '{}'::text[], $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: ATI Heat Shield + Rails
Barrel Length: 18.5"$$, $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: ATI Heat Shield + Rails
Barrel Length: 18.5"
Sight/Base: Winged Post &amp; Bead
Choke: Cylinder Bore
LOP Type: Adjustable
LOP: 10.75"-14.62"
Barrel Finish: Matte Blued
Stock Finish: 6-Pos Adjustable / Scorpion Recoil ATI
Akita Forend (Destroyer Gray/Black)
Weight: 6.75 lbs
Length: 36.37"
UPC: 015813504317$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (18, $$MAVERICK 88 SECURITTY$$, $$maverick-88-securitty$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/maverick-88-securitty.jpg$$, '{}'::text[], $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 18.5"$$, $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 18.5"
Sight/Base: Bead
Choke: Cylinder Bore
LOP Type: Fixed
LOP: 14.5"
Barrel Finish: Blued
Stock Finish: Synthetic (Black)
Weight: 6.25 lbs
Length: 39.5"
UPC: 049533310231$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (19, $$MAVERICK 88-TOP - FOLDING STOCK$$, $$maverick-88-top-folding-stock$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/maverick-88-top-folding-stock.jpg$$, '{}'::text[], $$SKU: 31027
Gauge: 12 Gauge
Action Type: Pump-Action
Chamber Size: 3"
Usage: Security
Barrel Length: 18.5"$$, $$SKU: 31027
Gauge: 12 Gauge
Action Type: Pump-Action
Chamber Size: 3"
Usage: Security
Barrel Length: 18.5"
Barrel Finish: Blued
Choke: Cylinder Bore
Capacity: 5+1
Length: 39.5"
LOP: 14.5"
LOP Type: Fixed
Sights: Bead
Stock: ATI Shotforce Top Folding Synthetic (Black)
Weight: 6 lbs
UPC: 049533310279$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (20, $$590M MAG-FED$$, $$590m-mag-fed$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/590m-mag-fed.jpg$$, '{}'::text[], $$SKU: 50206
Gauge: 12 Gauge
Action Type: Pump-Action
Chamber: 2.75"
Usage: Security
Barrel Type: Heavy-Walled
Barrel Length: 18.5"$$, $$SKU: 50206
Gauge: 12 Gauge
Action Type: Pump-Action
Chamber: 2.75"
Usage: Security
Barrel Type: Heavy-Walled
Barrel Length: 18.5"
Barrel Finish: Matte Blue
Choke: Accu-Choke System - Cylinder Bore Choke Installed
Capacity: 10+1 rounds
Length: 39.5"
LOP (Length of Pull): 13.87" (Fixed)
Sights: Ghost Ring Synthetic (Black)
Stock: Synthetic
Weight: 8 lbs
UPC: 015813502061$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (21, $$MAVERICK 88 - ALLPURPOSE$$, $$maverick-88-allpurpose$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/maverick-88-allpurpose.jpg$$, ARRAY['productos/maverick-88-allpurpose-2.jpg']::text[], $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 28"$$, $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 28"
Sight/Base: Dual Bead
Choke: Modified Tube
LOP Type: Fixed
LOP: 14.5"
Barrel Finish: Blued
Stock Finish: Synthetic (Black)
Weight: 7 lbs
Length: 47.75"
UPC: 049533310101$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (22, $$SECURITY/FIELD COMBO$$, $$security-field-combo$$, $$$$, $$escopetas$$, $$CA 12$$, $$productos/security-field-combo.jpg$$, '{}'::text[], $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 28"$$, $$Gauge: 12
Capacity: 5+1
Chamber: 3"
Barrel Type: Vent Rib
Barrel Length: 28"
Sight/Base: Dual Bead
Choke: Modified Tube
LOP Type: Fixed
LOP: 14.5"
Barrel Finish: Blued
Stock Finish: Synthetic (Black)
Weight: 7 lbs
Length: 47.75"
UPC: 049533310101$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (23, $$Glock 19 MOS Gen5 USA$$, $$glock-19-mos-gen5-usa$$, $$Glock$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/glock-19-mos-gen5-usa.webp$$, '{}'::text[], $$Mira de acero
15 tiros
Retén de corredera ambidiestro$$, $$Mira de acero
15 tiros
Retén de corredera ambidiestro$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (24, $$Glock 43x MOS gen5 Austria$$, $$glock-43x-mos-gen5-austria$$, $$Glock$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/glock-43x-mos-gen5-austria.webp$$, '{}'::text[], $$Mira de acero luminiscentes
10 tiros
Sistema MOS
Caja con seguridad$$, $$Mira de acero luminiscentes
10 tiros
Sistema MOS
Caja con seguridad$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (25, $$M&P 15 Cañón 14.5"$$, $$m-p-15-canon-14-5$$, $$Smith & Wesson$$, $$rifles$$, $$Cal. 5.56/223$$, $$productos/m-p-15-canon-14-5.webp$$, '{}'::text[], $$Proveedores 5.56mm NATO (223)
Mira mecánica ajustable
30 rondas$$, $$Proveedores 5.56mm NATO (223)
Mira mecánica ajustable
30 rondas$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (26, $$M&P 15-22 Sport Cañón 16"$$, $$m-p-15-22-sport-canon-16$$, $$Smith & Wesson$$, $$rifles$$, $$Calibre 22LR$$, $$productos/m-p-15-22-sport-canon-16.webp$$, '{}'::text[], $$Proveedores 22 LR
Mira mecánica ajustable
10+1 rondas$$, $$Proveedores 22 LR
Mira mecánica ajustable
10+1 rondas$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (27, $$Mossberg International 702 Plinkster$$, $$mossberg-international-702-plinkster$$, $$Mossberg$$, $$rifles$$, $$Calibre 22LR$$, $$productos/mossberg-international-702-plinkster.webp$$, '{}'::text[], $$Caliber: .22 LR
Barrel Lenght: 18"
Capacity: 10+1
Sight/Base: Adj FO Rifle
Twist: 1:16
LOP Type: Fixed
LOP: 14.25"
Barrel Finish: Blued
Stock Finish: Synthetic (Black)
Weight: 4
Lenght: 37"
UPC: 884110370723$$, $$Caliber: .22 LR
Barrel Lenght: 18"
Capacity: 10+1
Sight/Base: Adj FO Rifle
Twist: 1:16
LOP Type: Fixed
LOP: 14.25"
Barrel Finish: Blued
Stock Finish: Synthetic (Black)
Weight: 4
Lenght: 37"
UPC: 884110370723$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (28, $$M&P 15 Sport II OR$$, $$m-p-15-sport-ii-or$$, $$Smith & Wesson$$, $$rifles$$, $$Cal. 5.56/223$$, $$productos/m-p-15-sport-ii-or.webp$$, '{}'::text[], $$Proveedores 5.56mm NATO (223)
Miras incluídas
30 rondas$$, $$Proveedores 5.56mm NATO (223)
Miras incluídas
30 rondas$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (29, $$M&P 15-22 Sport Threaded Barrel$$, $$m-p-15-22-sport-threaded-barrel$$, $$Smith & Wesson$$, $$rifles$$, $$Calibre 22LR$$, $$productos/m-p-15-22-sport-threaded-barrel.webp$$, '{}'::text[], $$$$, $$$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (30, $$Mossberg 940 JM PRO$$, $$mossberg-940-jm-pro$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/mossberg-940-jm-pro.webp$$, '{}'::text[], $$Cañón 28"
Capacidad de 4+1$$, $$Cañón 28"
Capacidad de 4+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (31, $$Volunteer XV PRO 14.5"$$, $$volunteer-xv-pro-14-5$$, $$Volunteer$$, $$rifles$$, $$Cal. 5.56/223$$, $$productos/volunteer-xv-pro-14-5.webp$$, '{}'::text[], $$Proveedores 5.56mm NATO (223)
Mira mecánica ajustable
30 rondas$$, $$Proveedores 5.56mm NATO (223)
Mira mecánica ajustable
30 rondas$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (32, $$M&P 9 M2.0 COMPACT - Flat Dark Earth Finish$$, $$m-p-9-m2-0-compact-flat-dark-earth-finish$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/m-p-9-m2-0-compact-flat-dark-earth-finish.jpg$$, '{}'::text[], $$Modelo: M&amp;P®9 M2.0™ Compact
SKU: 13570
Tamaño del Marco: Compacto
Calibre: 9mm
Acción: Striker-Fired
Capacidad: 15+1 rondas$$, $$Modelo: M&amp;P®9 M2.0™ Compact
SKU: 13570
Tamaño del Marco: Compacto
Calibre: 9mm
Acción: Striker-Fired
Capacidad: 15+1 rondas
Longitud del Cañón: 3.6˝ (9.1 cm)
Ánima del Cañón: 1:10” RH, 5 Estrías
Mira Frontal: Punto Blanco - Alto
Mira Trasera: 2 Puntos Blancos - Altos
Ancho del Marco (Menos Controles): 1.16˝ (2.9 cm)
Altura Total: 5.0˝ (12.7 cm)
Longitud Total: 6.8˝ (17.3 cm)
Radio de la Mira: 5.9˝ (16.3 cm)
Agarre: Polímero
Peso: 25.9 oz. (734.3 g)
Material del Cañón: Acero Inoxidable con Acabado Armornite®
Material del Slide: Acero Inoxidable con Acabado Armornite®
Acabado del Slide: Negro Mate
Material del Marco: Polímero
Acabado del Marco: Negro Mate
Código UPC: 022188889543$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (33, $$Mossberg 940 JM PRO Optic Ready$$, $$mossberg-940-jm-pro-optic-ready$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/mossberg-940-jm-pro-optic-ready.webp$$, '{}'::text[], $$Cañón 24"
Capacidad de 9+1$$, $$Cañón 24"
Capacidad de 9+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (34, $$CZ Scorpion 3 Evo S1 Micro$$, $$cz-scorpion-3-evo-s1-micro$$, $$CZ$$, $$fusiles-semiautomaticos$$, $$Calibre 9 mm$$, $$productos/cz-scorpion-3-evo-s1-micro.webp$$, '{}'::text[], $$Proveedores (x1)
Rondas 20+1$$, $$Proveedores (x1)
Rondas 20+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (35, $$Mossberg Blaze$$, $$mossberg-blaze$$, $$Mossberg$$, $$rifles$$, $$Calibre 22LR$$, $$productos/mossberg-blaze.webp$$, '{}'::text[], $$Proveedores (x1)
Rondas 25+1$$, $$Proveedores (x1)
Rondas 25+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (36, $$Spec Ops Metal 4.6"$$, $$spec-ops-metal-4-6$$, $$Spec Ops$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/spec-ops-metal-4-6.webp$$, '{}'::text[], $$Color OD Greenal
Proveedores (x2)
Rondas 17+1
Controles extendidos$$, $$Color OD Greenal
Proveedores (x2)
Rondas 17+1
Controles extendidos$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (37, $$COMPETITOR M2.0-OR EDICION CAÑON DE 5” COLOR GRIS$$, $$competitor-m2-0-or-edicion-canon-de-5-color-gris$$, $$Smith & Wesson$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/competitor-m2-0-or-edicion-canon-de-5-color-gris.webp$$, '{}'::text[], $$Mira incluída Holosun HS407C BUND
Proveedores (x4)
Rondas 17+1
Controles extendidos$$, $$Mira incluída Holosun HS407C BUND
Proveedores (x4)
Rondas 17+1
Controles extendidos$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (38, $$Mossberg 940 Pro Waterfowl$$, $$mossberg-940-pro-waterfowl$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/mossberg-940-pro-waterfowl.webp$$, '{}'::text[], $$Cañón 28"
Capacidad 4+1$$, $$Cañón 28"
Capacidad 4+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (39, $$Affinity 3 MAX 5$$, $$affinity-3-max-5$$, $$Franchi$$, $$escopetas$$, $$CA 12$$, $$productos/affinity-3-max-5.webp$$, '{}'::text[], $$Cañón 28" SKU: A0520700
Calibre 12
Cañón 30" SKU: A050600
Capacidad de 4+1$$, $$Cañón 28" SKU: A0520700
Calibre 12
Cañón 30" SKU: A050600
Capacidad de 4+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (40, $$M2 Max 5$$, $$m2-max-5$$, $$Benelli$$, $$escopetas$$, $$CA 12$$, $$productos/m2-max-5.webp$$, '{}'::text[], $$Cañón 28"
Capacidad 4+1$$, $$Cañón 28"
Capacidad 4+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (41, $$Maverick 88 Camo Synthetic$$, $$maverick-88-camo-synthetic$$, $$Mossberg$$, $$escopetas$$, $$CA 12$$, $$productos/maverick-88-camo-synthetic.webp$$, '{}'::text[], $$Cañón 28"
Capacidad de 5+1$$, $$Cañón 28"
Capacidad de 5+1$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (42, $$Canik Mete MC9$$, $$canik-mete-mc9$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-mete-mc9.webp$$, ARRAY['productos/canik-mete-mc9-2.webp']::text[], $$Tamaño Micro Compacto
Calibre 9mm
OPTIC READY
Cargadores 12 y 15 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de miras de metal ajustables
Peso del gatillo 2 2,5 kg

Medidas y Peso:
Largo total 6,1”
Alto 4,52”
Largo del cañon 3,18”
Ancho 1,12“
Peso sin Cargador 603 gr$$, $$Tamaño Micro Compacto
Calibre 9mm
OPTIC READY
Cargadores 12 y 15 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de miras de metal ajustables
Peso del gatillo 2 2,5 kg

Medidas y Peso:
Largo total 6,1”
Alto 4,52”
Largo del cañon 3,18”
Ancho 1,12“
Peso sin Cargador 603 gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (43, $$Canik TP9 Sub Mete$$, $$canik-tp9-sub-mete$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-tp9-sub-mete.webp$$, '{}'::text[], $$Tamaño Micro Compacto
Calibre 9mm
OPTIC READY
Cargadores 12 y 15 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de miras de metal ajustables
Peso del gatillo 2 2,5 kg

Medidas y Peso:
Largo total 6,70”
Alto 4,60”
Largo del cañon 3,60”
Ancho 1,45 “
Peso sin Cargador 695gr$$, $$Tamaño Micro Compacto
Calibre 9mm
OPTIC READY
Cargadores 12 y 15 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de miras de metal ajustables
Peso del gatillo 2 2,5 kg

Medidas y Peso:
Largo total 6,70”
Alto 4,60”
Largo del cañon 3,60”
Ancho 1,45 “
Peso sin Cargador 695gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (44, $$Canik Mete SF$$, $$canik-mete-sf$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-mete-sf.webp$$, ARRAY['productos/canik-mete-sf-2.webp']::text[], $$Tamaño Micro Compacto
Calibre 9mm
OPTIC READY
Cargadores 15 y 15 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de mira delantera de fibra trasera de metal
Safety lever , seguro externo de gatillo
Peso del gatillo 2 2,5 kg

Medidas y Peso:
Largo total 7,28,”
Alto 5,23”
Largo del cañon 3,18”
Ancho 1,39“
Peso sin Cargador 795 gr$$, $$Tamaño Micro Compacto
Calibre 9mm
OPTIC READY
Cargadores 15 y 15 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de mira delantera de fibra trasera de metal
Safety lever , seguro externo de gatillo
Peso del gatillo 2 2,5 kg

Medidas y Peso:
Largo total 7,28,”
Alto 5,23”
Largo del cañon 3,18”
Ancho 1,39“
Peso sin Cargador 795 gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (45, $$Canik TP9 SF Elite S$$, $$canik-tp9-sf-elite-s$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-tp9-sf-elite-s.webp$$, '{}'::text[], $$Tamaño Compacto
Calibre 9mm
Cargadores 15 y 15 rondas
Empuñadura de polímero reforzad o
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de mira delantera de fibra trasera de metal
Peso del gatillo 2 2,5 kg
Safety lever : seguro externo de gatillo

Medidas y Peso:
Largo total 7,28,”
Alto 5,28”
Largo del cañon 4,19”
Ancho 1,46“
Peso sin Cargador 800 gr$$, $$Tamaño Compacto
Calibre 9mm
Cargadores 15 y 15 rondas
Empuñadura de polímero reforzad o
Indicador de cámara cargada
Picatinny Riel para accesorios.
Sistema de mira delantera de fibra trasera de metal
Peso del gatillo 2 2,5 kg
Safety lever : seguro externo de gatillo

Medidas y Peso:
Largo total 7,28,”
Alto 5,28”
Largo del cañon 4,19”
Ancho 1,46“
Peso sin Cargador 800 gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (46, $$Canik TP9 Elite S Combat$$, $$canik-tp9-elite-s-combat$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-tp9-elite-s-combat.webp$$, '{}'::text[], $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
3 Cargadores de 18 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios
Miras delantera de fibra óptica
Gatillo de Aluminio Flat
Safety lever : seguro externo

Medidas y Peso:
Largo total 7,28,”
Alto 5,96”
Largo del cañon 4,20”
Ancho 1,46“
Peso sin Cargador 830gr$$, $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
3 Cargadores de 18 rondas
Empuñadura de polímero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios
Miras delantera de fibra óptica
Gatillo de Aluminio Flat
Safety lever : seguro externo

Medidas y Peso:
Largo total 7,28,”
Alto 5,96”
Largo del cañon 4,20”
Ancho 1,46“
Peso sin Cargador 830gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (47, $$TP9 Elite Combat Executive$$, $$tp9-elite-combat-executive$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/tp9-elite-combat-executive.webp$$, '{}'::text[], $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
3 Cargadores de 18 rondas
Empuñadura de polímero reforz a d o
I ndicador de cámara cargada
Pi c a t inny R ie l para accesorios.
Miras delantera de fibra óptica
Gatillo de Aluminio Flat

Medidas y Peso:
Largo total 7,88”
Alto 5,96”
Largo del cañon 4,72”
Ancho 1,50“
Peso sin Cargador 845gr$$, $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
3 Cargadores de 18 rondas
Empuñadura de polímero reforz a d o
I ndicador de cámara cargada
Pi c a t inny R ie l para accesorios.
Miras delantera de fibra óptica
Gatillo de Aluminio Flat

Medidas y Peso:
Largo total 7,88”
Alto 5,96”
Largo del cañon 4,72”
Ancho 1,50“
Peso sin Cargador 845gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (48, $$TP9 Elite Combat Elven Dagger Special Box$$, $$tp9-elite-combat-elven-dagger-special-box$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/tp9-elite-combat-elven-dagger-special-box.webp$$, '{}'::text[], $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
3 Cargadores de 18 rondas
Empuñadura de polímero reforz a d o
I ndicador de cámara cargada
Pi c a t inny R ie l para accesorios.
Miras delantera de fibra óptica, mira trasera de metal
Gatillo de Aluminio Flat

Medidas y Peso:
Largo total 7,88”
Alto 5,96”
Largo del cañon 4,72”
Ancho 1,50“
Peso sin Cargador 845gr$$, $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
3 Cargadores de 18 rondas
Empuñadura de polímero reforz a d o
I ndicador de cámara cargada
Pi c a t inny R ie l para accesorios.
Miras delantera de fibra óptica, mira trasera de metal
Gatillo de Aluminio Flat

Medidas y Peso:
Largo total 7,88”
Alto 5,96”
Largo del cañon 4,72”
Ancho 1,50“
Peso sin Cargador 845gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (49, $$TP9 Elite Combat$$, $$tp9-elite-combat$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/tp9-elite-combat.webp$$, '{}'::text[], $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
2 Cargadores de 15 y 18 rondas
Empuñadura de polímero reforz a d o
I ndicador de cámara cargada
Pi c a t inny R ie l para accesorios.
Miras delantera de fibra óptica
Gatillo de Aluminio Flat

Medidas y Peso:
Largo total 7,88”
Alto 5,96”
Largo del cañon 4,20”
Ancho 1,50“
Peso sin Cargador 845gr$$, $$Tamaño Compacto
Cañon SAI Match Grade
Calibre 9mm
OPTIC READY
2 Cargadores de 15 y 18 rondas
Empuñadura de polímero reforz a d o
I ndicador de cámara cargada
Pi c a t inny R ie l para accesorios.
Miras delantera de fibra óptica
Gatillo de Aluminio Flat

Medidas y Peso:
Largo total 7,88”
Alto 5,96”
Largo del cañon 4,20”
Ancho 1,50“
Peso sin Cargador 845gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (50, $$Canik TTI Combat$$, $$canik-tti-combat$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-tti-combat.webp$$, '{}'::text[], $$CANIK CUSTOM W/TARAN TACTICAL
INNOVATIONS
Calibre 9mm / Optic Ready
Cargadores 18 Y 18 rondas +TTI extensiones +3
Barrel corte en espiral
Compensador Patentado por CANIK ( quick attached)
Carro agresivo con serraciones para fácil manejo
Sistema de mira delantera de fibra trasera de metal
Mira delantera HIVIZ de fibra óptica
Gatillo 90 90°Corte diamante
Incluye Maletín resistente al agua, MAGWELL, funda, accesorios varios

Medidas y Peso:
Largo total 7,87”
Alto 5,87”
Largo del cañon 4,6”
Ancho 1,41“
Peso sin Cargador 831gr$$, $$CANIK CUSTOM W/TARAN TACTICAL
INNOVATIONS
Calibre 9mm / Optic Ready
Cargadores 18 Y 18 rondas +TTI extensiones +3
Barrel corte en espiral
Compensador Patentado por CANIK ( quick attached)
Carro agresivo con serraciones para fácil manejo
Sistema de mira delantera de fibra trasera de metal
Mira delantera HIVIZ de fibra óptica
Gatillo 90 90°Corte diamante
Incluye Maletín resistente al agua, MAGWELL, funda, accesorios varios

Medidas y Peso:
Largo total 7,87”
Alto 5,87”
Largo del cañon 4,6”
Ancho 1,41“
Peso sin Cargador 831gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (51, $$SFX Rival Grey$$, $$sfx-rival-grey$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/sfx-rival-grey.webp$$, '{}'::text[], $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de polí m ero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, trasera ajustable
Gatillo 90 90°de aluminio, corte diamante

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,41“
Peso sin Cargador 835gr$$, $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de polí m ero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, trasera ajustable
Gatillo 90 90°de aluminio, corte diamante

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,41“
Peso sin Cargador 835gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (52, $$SFX Rival Dark Side$$, $$sfx-rival-dark-side$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/sfx-rival-dark-side.webp$$, '{}'::text[], $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de polí m ero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, trasera ajustable
Gatillo 90 90°de aluminio, corte diamante

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,41“
Peso sin Cargador 835gr$$, $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de polí m ero reforzado
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, trasera ajustable
Gatillo 90 90°de aluminio, corte diamante

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,41“
Peso sin Cargador 835gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (53, $$SFX Rival-S Chrome$$, $$sfx-rival-s-chrome$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/sfx-rival-s-chrome.webp$$, '{}'::text[], $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de metal
Carro con serraciones y empuñadura agresiva
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, mira trasera ajustable
Gatillo 90 90°de aluminio, corte diamante
Magwell de competencia

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,45“
Peso sin Cargador 1210gr$$, $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de metal
Carro con serraciones y empuñadura agresiva
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, mira trasera ajustable
Gatillo 90 90°de aluminio, corte diamante
Magwell de competencia

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,45“
Peso sin Cargador 1210gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (54, $$SFX Rival-S Dark Side$$, $$sfx-rival-s-dark-side$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/sfx-rival-s-dark-side.webp$$, '{}'::text[], $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de metal
Carro con serraciones y empuñadura agresiva
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, mira trasera ajustable
Gatillo 90 90°de aluminio, corte diamante
Magwell de competencia

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,45“
Peso sin Cargador 1210gr$$, $$Tamaño FULL SIZE LONG SLIDE
Calibre 9mm / OPTIC READY
2 Cargadores de 18 y 18 rondas
Empuñadura de metal
Carro con serraciones y empuñadura agresiva
Indicador de cámara cargada
Picatinny Riel para accesorios.
Miras delantera de fibra óptica, mira trasera ajustable
Gatillo 90 90°de aluminio, corte diamante
Magwell de competencia

Medidas y Peso:
Largo total 8,09”
Alto 5,70”
Largo del cañon 5,00”
Ancho 1,45“
Peso sin Cargador 1210gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (55, $$Canik Mete SFT$$, $$canik-mete-sft$$, $$Canik$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/canik-mete-sft.webp$$, ARRAY['productos/canik-mete-sft-2.webp']::text[], $$Tamaño FULL SIZE
Calibre 9mm / OPTIC READY
2 Cargadores 20 y 20 rondas
Empuñadura de polímero reforzado
Carro con serraciones y empuñadura agresiva
Picatinny Riel para accesorios.
Indicador de cámara cargada
Miras delantera y mira trasera de metal
Magwell incluido

Medidas y Peso:
Largo total 8,87”
Alto 5,70”
Largo del cañon 4,46”
Ancho 1,50“
Peso sin Cargador 815 gr$$, $$Tamaño FULL SIZE
Calibre 9mm / OPTIC READY
2 Cargadores 20 y 20 rondas
Empuñadura de polímero reforzado
Carro con serraciones y empuñadura agresiva
Picatinny Riel para accesorios.
Indicador de cámara cargada
Miras delantera y mira trasera de metal
Magwell incluido

Medidas y Peso:
Largo total 8,87”
Alto 5,70”
Largo del cañon 4,46”
Ancho 1,50“
Peso sin Cargador 815 gr$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (56, $$Glock 45 Gen5$$, $$glock-45-gen5$$, $$Glock$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/glock-45-gen5.webp$$, '{}'::text[], $$Miras de acero luminiscentes
Cañón 4.2"
17 tiros
Sistema MOS
Safe Action System$$, $$Miras de acero luminiscentes
Cañón 4.2"
17 tiros
Sistema MOS
Safe Action System$$);
insert into products (id, name, slug, brand, category, caliber, image, gallery, short_desc, full_desc) values (57, $$Glock 26 Gen5$$, $$glock-26-gen5$$, $$Glock$$, $$pistolas$$, $$Calibre 9 mm$$, $$productos/glock-26-gen5.webp$$, '{}'::text[], $$Miras de acero luminiscentes
12 tiros
Sistema MOS
Caja con seguridad
Retén corredera ambidiestro$$, $$Miras de acero luminiscentes
12 tiros
Sistema MOS
Caja con seguridad
Retén corredera ambidiestro$$);
select setval(pg_get_serial_sequence('products','id'), (select max(id) from products));

-- ----- Datos semilla: paquetes -----
delete from paquetes;
insert into paquetes (id, title, price, items, featured, sort_order) values (1, $$Paquete de 1 arma$$, $$$ 55$$, ARRAY['Pistola 9mm (25 tiros)']::text[], false, 1);
insert into paquetes (id, title, price, items, featured, sort_order) values (2, $$Paquete de 1 arma$$, $$$ 75$$, ARRAY['Pistola 9mm (50 tiros)']::text[], false, 2);
insert into paquetes (id, title, price, items, featured, sort_order) values (3, $$Paquete de 5 armas$$, $$$ 160$$, ARRAY['Pistola (25 tiros)', 'Rifle AR9 (25 tiros)', 'Rifle (20 tiros)', 'Escopeta (10 tiros)', 'Revólver (10 tiros)']::text[], true, 3);
insert into paquetes (id, title, price, items, featured, sort_order) values (4, $$Paquete de 4 armas$$, $$$ 140$$, ARRAY['Pistola (50 tiros)', 'Rifle (20 tiros)', 'Escopeta (10 tiros)', 'Revólver (10 tiros)']::text[], false, 4);
insert into paquetes (id, title, price, items, featured, sort_order) values (5, $$Paquete de 3 armas$$, $$$ 120$$, ARRAY['Pistola (50 tiros)', 'Rifle (20 tiros)', 'Escopeta (10 tiros)']::text[], false, 5);
select setval(pg_get_serial_sequence('paquetes','id'), (select max(id) from paquetes));

-- ----- Datos semilla: slides -----
delete from slides;
insert into slides (id, kicker, title, accent, body, image, btn1_text, btn1_url, btn2_text, btn2_url, sort_order, active) values (1, $$Venta de Armas en Chiriquí$$, $$Magnum Guns$$, $$& Ammo Shop$$, $$Venta de armas en Chiriquí, municiones y equipos de seguridad. Con años de experiencia en el mercado, ofrecemos productos de alta calidad y asesoramiento personalizado para que tomes decisiones seguras y bien informadas.$$, $$/assets/img/banner-1.jpg$$, $$Ver Catálogo$$, $$/catalogo/$$, $$Conócenos$$, $$/sobre-nosotros/$$, 1, true);
insert into slides (id, kicker, title, accent, body, image, btn1_text, btn1_url, btn2_text, btn2_url, sort_order, active) values (2, $$Polígono & Campo de Tiro$$, $$Practica con$$, $$Seguridad$$, $$Contamos con polígono de tiro cerrado y campo de tiro al aire libre, con supervisión de expertos y paquetes para todos los niveles. Reserva tu sesión de tiro.$$, $$/assets/img/banner-2.jpg$$, $$Reservar Sesión$$, $$/paquetes-de-tiro/$$, $$Campo de Tiro$$, $$/campo-de-tiro/$$, 2, true);
insert into slides (id, kicker, title, accent, body, image, btn1_text, btn1_url, btn2_text, btn2_url, sort_order, active) values (3, $$Trámites & Permisos$$, $$Permiso de Armas$$, $$en Panamá$$, $$Te acompañamos en cada paso: trámite de arma nueva, renovación de permiso e inclusión de armas. Asesoría personalizada para que cumplas con la normativa sin complicaciones.$$, $$/assets/img/banner-3.jpg$$, $$Conocer Más$$, $$/tramites-permiso-de-armas-en-panama/$$, $$Contáctanos$$, $$/contacto/$$, 3, true);
select setval(pg_get_serial_sequence('slides','id'), (select max(id) from slides));
